Django/formclass/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # User [C]reate
    path('login/', views.login, name='login'), # Session [C]reate   
    path('logout/', views.logout, name='logout'), # Session [D]elete
    path('delete/', views.delete, name='delete'), # User [D]elete
    path('edit/', views.edit, name='edit'), # User [U]pdate
    path('password/', views.password, name='password'), # Password [U]pdate
    path('profile/', views.profile_detail, name='profile_detail'), # Profile [R]ead
    path('profile/edit/', views.profile_edit, name='profile_edit'), # Profile [U]pdate
    path('<str:username>/', views.profile, name='profile'),
]

Django/formclass/formclass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

#static으로 주소를 만들어줌 
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

Django/formclass/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:profile_detail' %}">
            {{ user.username }}
        </a>
        
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Logout">
        </form>
        

        {% else %}
        <a href="{% url 'accounts:login' %}">Login</a>
        <a href="{% url 'accounts:signup' %}">Signup</a>
        {% endif %}
    </nav>
    {% block body %}

    {% endblock %}
</body>
</html>