CRUD_practice/crud-practice-master/crud-practice-master/crud_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

CRUD_practice/crud-practice-master/crud-practice-master/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

CRUD_practice/crud-practice-master/crud-practice-master/movies/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField(default=0)
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField(default=0)
    poster_url = models.TextField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

CRUD_practice/crud-practice-master/crud-practice-master/movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'title_en', 
                'audience', 'open_date', 'genre', 'watch_grade',
                'score', 'poster_url', 'description',)

CRUD_practice/crud-practice-master/crud-practice-master/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


def new(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/new.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.delete()
    return redirect('movies:index')


def edit(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form': form,
    }
    return render(request, 'movies/edit.html', context)

CRUD_practice/crud-practice-master/crud-practice-master/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie Detail</h1>

<p>Title: {{ movie.title }}</p>
<p>Title En: {{ movie.title_en }}</p>
<p>Audience: {{ movie.audience }}</p>
<p>Open Date: {{ movie.open_date }}</p>
<p>Genre: {{ movie.genre }}</p>
<p>Watch Grade: {{ movie.watch_grade }}</p>
<p>Score: {{ movie.score }}</p>
<p>Poster URL: <img src="{{ movie.poster_url }}" alt="Movie Poster" width="300px"></p>
<p>Description: {{ movie.description }}</p>
<p>Created At: {{ movie.created_at }}</p>
<p>Updated At: {{ movie.updated_at }}</p>

<a href="{% url 'movies:index' %}">Index</a>
<a href="{% url 'movies:edit' movie.pk %}">Edit</a>
<form action="{% url 'movies:delete' movie.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

{% endblock %}

CRUD_practice/crud-practice-master/crud-practice-master/movies/templates/movies/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie Edit</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

{% endblock %}

CRUD_practice/crud-practice-master/crud-practice-master/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie Index</h1>

<a href="{% url 'movies:new' %}">New</a>

<ul>
  {% for movie in movies %}
  <li>
    <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

CRUD_practice/crud-practice-master/crud-practice-master/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block body %}

<h1>Movie New</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>

{% endblock %}

CRUD_practice/crud-practice-master/crud-practice-master/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>