Django/crud/articles/urls.py
# 복사한 urls.py 임
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'articles'


urlpatterns = [
    # 1. GET /articles/
    path('', views.index, name='index'), #게시글 목록
    # send / receive
    # 2. GET / articles/new/
    path('new/', views.new, name='new'), #<- 게시글 작성 양식
    # 3. POST / articles/new/
    # path('create/', views.create, name='create'), #<-게시글
    # 4. GET /articles/1/
    path('<int:pk>/', views.detail, name='detail'),
    # 5. POST(<-DELETE) /articles/1/ :update역할
    path('<int:pk>/delete/', views.delete, name='delete'),
    # 6. GET /articles/edit/1/
    path('<int:pk>/edit/' , views.edit, name='edit'), #게시글 수정양식(GET)
    # #7. PUT,POST /articles/update/1/
    # path('update/<int:pk>/', views.update, name='update') #게시글 수정!(POST)
    # 
]

Django/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django/crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

Django/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
        # Database 조회(꺼내오기)
    articles = Article.objects.all() #<- DB에 있는 게시글 데이터 전부!
    context = {
        'articles': articles,
       
    }
    return render(request, 'articles/index.html',context)

def new(request): #<-GET
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        # 데이터베이스에 저장
        # 1. Article 인스턴스 생성
        article = Article(title=title, content=content)
        # 2. save!
        article.save()

        return redirect('articles:detail', article.pk)
    else:
        context = {

        }
        return render(request, 'articles/new.html',context)

#get으로 보낸요청은 get로만 받아야함
#post도 마찬가지
def create(request): #<-POST
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 데이터베이스에 저장
    # 1. Article 인스턴스 생성
    article = Article(title=title, content=content)
    # 2. save!
    article.save()

    return redirect('articles:detail', article.pk)
    # context = {
    #     'title':title,
    #     'content': content,                  <-필요없어짐 
    # }

    #return render(request, 'articles/create.html',context) <-필요없어짐 
    
def detail(request, pk):
    # Database 조회: 단 하나의 data
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk): # POST
    #Database 삭제 (조회+삭제)
    # 1. 조회
    article = Article.objects.get(pk=pk)
    # 2. 삭제 명령
    article.delete()

    return redirect('/articles/index/')

def edit(request, pk): #GET
    # 1. 조회
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        # 게시글 수정!
        title = request.POST.get('title')
        content = request.POST.get('content')
        # database 조회 + 수정
        # 2. 수정
        article.title = title
        article.content = content
        # 3. 저장
        article.save()

        return redirect('detail',article.pk)
    else:
        #게시글 수정 양식!

        # Database 조회(+ 저장)
        # 1. 조회
        # 2. 저장
        context = {
            'article': article,
        }
        return render(request, 'articles/edit.html',context)

def update(request, pk): #POST
    title = request.POST.get('title')
    content = request.POST.get('content')

    # database 조회 + 수정
    # 1. 조회
    article = Article.objects.get(pk=pk)
    # 2. 수정
    article.title = title
    article.content = content
    # 3. 저장
    article.save()

    return redirect('detail',article.pk)

Django/crud/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Create</h1>

<h2>제목: {{ title }}</h2>

<p>내용: {{ content }}</p>
{% endblock %}

Django/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Detail</h1>

<ul>
    <li>PK: {{article.pk}}</li>
    <li>제목: {{ article.title }}</li>
    <li>내용: {{ article.content }}</li>
    <li>작성시간: {{ article.created_at }}</li>
    <li>수정시각: {{ article.updated_at }}</li>
</ul>

<a href="{% url 'articles:index' %}">목록</a>

<a href="{% url 'articles:edit' article.pk %}">수정</a>


<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제!!">
</form>



{% endblock %}

Django/crud/articles/templates/articles/edit.html
{% extends 'base.html'%}

{% block body %}

<h1>Article Edit</h1>

<form action="" method='POST'>
    {% csrf_token %}
    <label for="title">제목</label>
    <input id='title' type="text" name='title' value="{{ article.title }}">
    <label for="content">내용</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
    <input type="submit" value='Update!'>
</form>

{% endblock %}

Django/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Index</h1>

{% for article in articles %}
    <ul>
        <li>{{ article.id }}</li>
        
        <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
        <li>{{ article.content }}</li>
        <hr>
    </ul>
{% endfor %}
<!-- 게시판에서 세 글 쓰기 링크 만들기 -->
<a href="{% url 'articles:new' %}">New Article</a>

{% endblock %}

Django/crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block body %}

<h1>Article New</h1>

<!-- method='POST': 요청을 POST로 하게 바꾸기 -->
<form action=" " method='POST'>
    {% csrf_token %}
    <label for="title">제목</label>
    <input id='title' type="text" name='title'>
    <label for="content">내용</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value='Create!'>
</form>

{% endblock %}

Django/crud/crud/templates/base.html
<!-- "공공 템플릿이라고 생각하면 됨" -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>